experiment:
  name: weeddetection
  group: VerFlip
  continue_with_errors: False
  start_from_grid: 0
  start_from_run: 0
  tracking_dir: null
  entity: pasqualedem
  excluded_files: "*.pth"

parameters:
  tags: [[]]
  # train, test, inference
  # phases: [[run]]
  phases: [[train, test]]

  train_params:
    max_epochs: [500]
    initial_lr: [0.0001]
    optimizer: [Adam]
    optimizer_params:
      weight_decay: [0, 0.0005]
    loss:
      name: [cross_entropy]
      params:
        weight: [[0.0273, 1.0, 4.3802]]
    # ema: True
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    metric_to_watch: [JaccardIndex]

  early_stopping:
    enabled: [True]
    params:
      patience: [10]
      monitor: [loss]
      mode: [min]

  train_metrics:
    jaccard:
      num_classes: [3]
    f1:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]
  test_metrics:
    jaccard:
      num_classes: [3]
    auc:
      num_classes: [3]
    conf_mat:
      num_classes: [3]
    f1:
      num_classes: [3]
      average: [macro]
      mdmc_average: [global]
    precision:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]
    recall:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]
    perclassauc:
      discriminator: # To discriminate between different classes
        [[
          ['auc_background', 0],
          ['auc_crop', 1],
          ['auc_weed', 2]
        ]]

  model:
    name: [regseg48, segnet]
    params: [{}]

  dataset:
    root: ["dataset/processed/Sequoia"]
    train_folders: [['006', '007']]
    test_folders: [['005']]
    hor_flip: [True]
    ver_flip: [True]
    # channels: ['CIR', ['G', 'NDVI', 'NIR', 'R', 'RE']]
    # channels: [['R', 'G'], 'CIR', ['R', 'G', 'RE', 'NIR'], ['G', 'NDVI', 'NIR', 'R', 'RE']]
    # channels: [['R', 'G', 'RE', 'NIR']]
    # channels: [['R', 'G']]
    channels: [['R', 'G'], ['NDVI'], 'CIR', ['G', 'NIR', 'R'], ['R', 'G', 'RE', 'NIR'], ['G', 'NDVI', 'NIR', 'R', 'RE']]
    batch_size: [6]
    val_batch_size: [24]
    test_batch_size: [24]
    num_workers: [0]
    num_classes: [3]
    size: [[368, 496]]
    return_path: [True]

  run_params:
    batch_size: [24]
    run_folders: [["007"]]


other_grids:
  null