experiment: Try

train_params:
  max_epochs: 1
  initial_lr: 3e-4
  optimizer: Adam
  loss:
    name: cross_entropy
    params:
      weight: [0.0273, 1.0, 4.3802]
  ema: True
  zero_weight_decay_on_bias_and_bn: True
  metric_to_watch: JaccardIndex

metrics:
  jaccard:
      num_classes: 3

dataset:
  root: "dataset/processed/Sequoia"
  batch_size: 6
  val_batch_size: 12
  test_batch_size: 12
  num_workers: 4