experiment:
  name: Fifth experiment
  description: This is the fifth experiment
  continue_with_errors: True
  mlruns_folder: None


parameters:
  run_hash: [None]
  details: [With flip]
  # train, test, run
  # phases: [[run]]
  phases: [[train, test, run]]

  train_params:
    max_epochs: [500]
    initial_lr: [0.001]
    optimizer: [SGD]
    optimizer_params:
      momentum: [0.9]
      weight_decay: [0.0005]
    loss:
      name: [cross_entropy]
      params:
        weight: [[0.0273, 1.0, 4.3802]]
    # ema: True
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    metric_to_watch: [JaccardIndex]

  early_stopping:
    enabled: [True]
    params:
      patience: [5]
      monitor: [loss]
      mode: [min]

  train_metrics:
    jaccard:
      num_classes: [3]
  test_metrics:
    jaccard:
      num_classes: [3]
    auc:
      num_classes: [3]
    perclassauc:
      discriminator: # To discriminate between different classes
        [[
          ['auc_background', 0],
          ['auc_crop', 1],
          ['auc_weed', 2]
        ]]

  model:
    name: [segnet]
    params: [{}]

  dataset:
    root: ["dataset/processed/Sequoia"]
    train_folders: [['005', '006']]
    test_folders: [['007']]
    # channels: [['G', 'NDVI', 'NIR', 'R', 'RE']]
    channels: [['R', 'G'],'CIR', ['G', 'NIR', 'R'], ['R', 'G', 'RE', 'NIR'], ['G', 'NDVI', 'NIR', 'R', 'RE']]
    # channels: [['R', 'G', 'RE', 'NIR']]
    # channels: [['R', 'G']]
    batch_size: [6]
    val_batch_size: [12]
    test_batch_size: [12]
    num_workers: [0]
    num_classes: [3]
    size: [same]

  test_params:
    init_sg_loggers: [True]

  run_params:
    batch_size: [24]
    run_folders: [["005"]]
    init_sg_loggers: [False]
    prediction_folder: [mlflow] # "mlflow" to make into artifact folder